dist: bionic
language: go
go:
  - 1.12.17
# https://docs.travis-ci.com/user/customizing-the-build#setting-symlinks-option
git:
  symlinks: true
# https://docs.travis-ci.com/user/installing-dependencies/
addons:
  apt:
    packages:
    - wget
    - make
    - git
    - gettext
install:
  - cd tipitaka/
  - make install
script:
  - make make-sutta
deploy:
  - provider: pages
    repo: siongui/tipitaka.sutta.org
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: tipitaka/website
    on:
      branch: master
