name: Build Pāli Dictionary Website for sutta.org and online-dhamma.net

on:
  push:
    branches:
      - master

jobs:
  build-sutta:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    - uses: actions/setup-go@v2
      with:
        go-version: '1.12.17'
    - name: Install dependencies
      run: |
        cd dictionary/
        make install
    - name: Build Pāli Dictionary Website for sutta.org
      run: |
        cd dictionary/
        make make-sutta
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dictionary/website
        CLEAN: true
