name: Build Pāli Website

on:
  push:
    branches:
      - master

jobs:

  build-dic-sutta:
    runs-on: ubuntu-latest
    #if: ${{ false }}
    env:
      TARGET_WEBSITE: sutta
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    - uses: actions/setup-go@v2
      with:
        go-version: '1.12.17'
    - name: Install dependencies
      run: |
        cd dictionary/
        make install
    - name: Build Pāli Dictionary Website for dictionary.sutta.org
      run: |
        cd dictionary/
        make make-sutta
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        REPOSITORY_NAME: siongui/dictionary.sutta.org
        BRANCH: gh-pages
        FOLDER: dictionary/website
        CLEAN: true

  build-dic-dhamma:
    runs-on: ubuntu-latest
    #if: ${{ false }}
    env:
      TARGET_WEBSITE: dhamma
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    - uses: actions/setup-go@v2
      with:
        go-version: '1.12.17'
    - name: Install dependencies
      run: |
        cd dictionary/
        make install
    - name: Build Pāli Dictionary Website for dictionary.online-dhamma.net
      run: |
        cd dictionary/
        make make-dhamma
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        REPOSITORY_NAME: siongui/dictionary.online-dhamma.net
        BRANCH: gh-pages
        FOLDER: dictionary/website
        CLEAN: true

  build-dic-offline:
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    - uses: actions/setup-go@v2
      with:
        go-version: '1.12.17'
    - name: Install dependencies
      run: |
        cd dictionary/
        make install
        make lib_goef
    - name: Build Pāli Dictionary Offline Website
      run: |
        cd dictionary/
        make offline
    #    make mvofflinetopublic
    #- name: Deploy
    #  uses: JamesIves/github-pages-deploy-action@3.7.1
    #  with:
    #    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #    REPOSITORY_NAME: siongui/offline-pali-dictionary
    #    BRANCH: gh-pages
    #    FOLDER: public
    #    CLEAN: true

  build-tpk-sutta:
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    - uses: actions/setup-go@v2
      with:
        go-version: '1.12.17'
    - name: Install dependencies
      run: |
        cd tipitaka/
        make install
    - name: Build Pāli Tipiṭaka Website for tipitaka.sutta.org
      run: |
        cd tipitaka/
        make make-sutta
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        REPOSITORY_NAME: siongui/tipitaka.sutta.org
        BRANCH: gh-pages
        FOLDER: tipitaka/website
        CLEAN: true
